# Generated by Django 5.2.16 on 2026-07-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Standup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("standup_date", models.DateField()),
                ("blockers", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-standup_date"],
            },
        ),
        migrations.CreateModel(
            name="StandupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "What did I do?"),
                            ("CURRENT", "What am I working on?"),
                            ("PLANNED", "What do I plan to do?"),
                            ("MEETING", "Meetings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="standups.standup",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="standup",
            index=models.Index(fields=["standup_date"], name="standups_st_standup_2942f2_idx"),
        ),
        migrations.AddConstraint(
            model_name="standup",
            constraint=models.UniqueConstraint(
                fields=("user", "standup_date"), name="unique_standup_per_user_per_date"
            ),
        ),
        migrations.AddIndex(
            model_name="standupitem",
            index=models.Index(
                fields=["standup", "section", "position"], name="standups_st_standup_9b71a4_idx"
            ),
        ),
    ]
