# Generated by Django 5.2.16 on 2026-07-16 13:42

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequestLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(validators=[common.validators.validate_https_url])),
                ("group_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In review"),
                            ("CHANGES_REQUESTED", "Changes requested"),
                            ("APPROVED", "Approved"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("week_start", models.DateField(validators=[common.validators.validate_monday])),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pull_request_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "group_name", "position", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-week_start", "group_name", "position"],
                        name="pull_reques_week_st_3f0d09_idx",
                    ),
                    models.Index(fields=["status"], name="pull_reques_status_baadc0_idx"),
                ],
            },
        ),
    ]
